name: Monitor Spain Visa Status

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 1: Download previous hash artifact
    - name: Download last_hash.txt (if exists)
      uses: actions/download-artifact@v4
      with:
        name: last-hash-file # Name of the artifact
        path: . # Download to the current directory

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run status monitor
      run: python monitor_spain.py
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}

    # Step 2: Upload the updated hash artifact
    - name: Upload last_hash.txt
      uses: actions/upload-artifact@v4
      with:
        name: last-hash-file # Must match the download name
        path: last_hash.txt # Path to the file to upload
        # Optional: retention-days: 1 # How long to keep the artifact (e.g., 1 day)
