name: Monitor Spain Visa Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 1: Download previous hash artifact
    - name: Download last_hash.txt (if exists)
      uses: actions/download-artifact@v4
      with:
        name: last-hash-file
        path: .
        fail-on-unmatched-files: false # Crucial for first run/missing artifact tolerance

    # --- DEBUGGING STEP START ---
    - name: Verify last_hash.txt after download
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files in current directory (including hidden files):"
        ls -la
        if [ -f last_hash.txt ]; then
          echo "SUCCESS: last_hash.txt FOUND after download step!"
          echo "Content of last_hash.txt:"
          cat last_hash.txt
        else
          echo "WARNING: last_hash.txt NOT FOUND after download step."
        fi
    # --- DEBUGGING STEP END ---

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run status monitor
      run: python monitor_spain.py
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}

    - name: Upload last_hash.txt
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: last-hash-file
        path: last_hash.txt
